name: Build pandas
description: Rebuilds the C extensions and installs pandas
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        pip install -e . --no-build-isolation -v
      shell: bash -el {0}
