name: "ASV Bot"

on:
  # TODO: remove this, testing purposes only
  pull_request:
    branches:
      - master
  issue_comment: # Pull requests are issues
    types:
      - created

env:
  ENV_FILE: environment.yml

jobs:
  autotune:
    name: "Run benchmarks"
    # TODO: Support more benchmarking options later, against different branches, against self, etc
    #if: startsWith(github.event.comment.body, '@github-actions benchmark')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
        # Don't install the full conda environment, asv will do that by itself
      - name: Install ASV
        run: |
          pip install asv

      - name: Run benchmarks
        id: bench
        run: |
          cd asv_bench
          asv check -E existing
          git remote add upstream https://github.com/pandas-dev/pandas.git
          git fetch upstream
          asv machine --yes
          asv continuous -f 1.1 upstream/master HEAD -b ^io.csv.ReadCSVEngine # TODO: remove io.csv part once working
          echo "BENCH_OUTPUT=$(asv compare upstream/master HEAD)" >> $GITHUB_ENV
          # export BENCH_OUTPUT=$(asv compare upstream/master HEAD)

      - name: Debug
        run: |
          echo $BENCH_OUTPUT

      - uses: actions/github-script@v4
        env:
          BENCH_OUTPUT: $BENCH_OUTPUT
        with:
          script: |
            const BENCH_OUTPUT = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: JSON.stringify(`${BENCH_OUTPUT}`)
            })
