name: "ASV Bot"

on:
  # TODO: remove this, testing purposes only
  pull_request:
    branches:
      - master
  issue_comment: # Pull requests are issues
    types:
      - created

env:
  ENV_FILE: environment.yml

jobs:
  autotune:
    name: "Run benchmarks"
    # TODO: Support more benchmarking options later, against different branches, against self, etc
    #if: startsWith(github.event.comment.body, '@github-actions benchmark')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('${{ env.ENV_FILE }}') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pandas-dev
          channel-priority: strict
          environment-file: ${{ env.ENV_FILE }}
          use-only-tar-bz2: true

      - name: Run benchmarks
        run: |
          cd asv_bench
          asv check -E existing
          git remote add upstream https://github.com/pandas-dev/pandas.git
          git fetch upstream
          asv machine --yes
          asv continuous -f 1.1 upstream/master HEAD -b ^io.csv # TODO: remove io.csv part once working
          export BENCH_OUTPUT = $(asv compare upstream/master HEAD)

      - uses: actions/github-script@v4
        with:
          script: |
            const BENCH_OUTPUT = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${BENCH_OUTPUT}`
            })
          
