name: "ASV Bot"

on:
  # TODO: remove this, testing purposes only
  pull_request:
    branches:
      - master
  issue_comment: # Pull requests are issues
    types:
      - created

env:
  ENV_FILE: environment.yml

jobs:
  autotune:
    name: "Run benchmarks"
    # TODO: Support more benchmarking options later, against different branches, against self, etc
    #if: startsWith(github.event.comment.body, '@github-actions benchmark') # TODO: uncomment me once final
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      # Set concurrency to prevent abuse(full runs are ~5.5 hours !!!)
      # each user can only run one concurrent benchmark bot at a time
      # We don't cancel in progress jobs, but if you want to benchmark multiple PRs, you're gonna have
      # to wait
      group: ${{ github.actor }}-asv
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('${{ env.ENV_FILE }}') }}

      - name: Cache asv environment
        uses: actions/cache@v2
        with:
          path: pandas/asv_bench/env
          key: ${{ runner.os }}-conda-${{ hashFiles('${{ env.ENV_FILE }}') }}

        # Although asv sets up its own env, deps are still needed
        # during discovery process
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pandas-dev
          channel-priority: strict
          environment-file: ${{ env.ENV_FILE }}
          use-only-tar-bz2: true

      - name: Run benchmarks
        id: bench
        continue-on-error: true # This is a fake failure, asv will exit code 1 for regressions
        run: |
          cd asv_bench
          asv check -E existing
          git remote add upstream https://github.com/pandas-dev/pandas.git
          git fetch upstream
          asv machine --yes
          asv continuous upstream/master HEAD -b ^io # TODO: Add back -f 1.1
          echo 'BENCH_OUTPUT<<EOF' >> $GITHUB_ENV
          asv compare -f 1.1 upstream/master HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - uses: actions/github-script@v4
        env:
          BENCH_OUTPUT: ${{env.BENCH_OUTPUT}}
        with:
          script: |
            const ENV_VARS = process.env
            console.log(ENV_VARS["BENCH_OUTPUT"])
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ENV_VARS["BENCH_OUTPUT"]
            })
