# This bot updates the issue with number DEPRECATION_TRACKER_ISSUE
# with the PR number that issued the deprecation.

# It runs on commits to main, and will trigger if the PR linked to a merged commit has the "Deprecate" label
name: Deprecations Bot

on:
  push:
    branches:
      - test


permissions:
  contents: read

jobs:
  deprecation_update:
    permissions:
      issues: write
    runs-on: ubuntu-22.04
    env:
      DEPRECATION_TRACKER_ISSUE: 35
    steps:
    - uses: actions/github-script@v6
      id: update-deprecation-issue
      with:
        script: |
          body = github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${DEPRECATION_TRACKER_ISSUE},
          })["body"]
          // Add the PR number to body
          // (we always get the first linked PR)
          linkedPR = github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: ${{ github.sha }}
          })[0]
          
          isDeprecation = false
          for (label in linkedPR["labels"]) {
            if (label["name"] == "Deprecate") {
              isDeprecation = true;
              break;
            }
          }
          
          PR_NUMBER = linkedPR["number"];
          
          body += ("- [ ] #" + PR_NUMBER);
          github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${DEPRECATION_TRACKER_ISSUE},
            body: body
          })
    - name: Checkout
      run: |
        echo "Adding deprecation PR number to deprecation tracking issue"
        export PR=${{ github.event.pull_request.number }}
        BODY=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${DEPRECATION_TRACKER_ISSUE} |
          python3 -c "import sys, json, os; x = {'body': json.load(sys.stdin)['body']}; pr = os.environ['PR']; x['body'] += f'\n- [ ] #{pr}'; print(json.dumps(x))")
        echo ${BODY}
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X PATCH -d "${BODY}" https://api.github.com/repos/${{ github.repository }}/issues/${DEPRECATION_TRACKER_ISSUE}
