name: Python Dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: actions-310-dev
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python Dev Version
      uses: actions/setup-python@v2
      with:
        python-version: '3.10-dev'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install git+https://github.com/numpy/numpy.git
        pip install git+https://github.com/pytest-dev/pytest.git
        pip install git+https://github.com/nedbat/coveragepy.git
        pip install cython python-dateutil pytz hypothesis pytest-xdist
        pip list
    - name: Build Pandas
      run: |
        python setup.py build_ext -q -j2
        python -m pip install -e . --no-build-isolation --no-use-pep517

    - name: Build Version
      run: |
        python -c "import pandas; pandas.show_versions();"
    - name: Test numpy/pandas
      run: |
        python -c "import numpy as np; print(np.core.numeric.dtype); print(np.iinfo(np.int64).max)"
        python -c "import numpy as np; print(np.core.numeric.dtype(np.int64))"
        python -c "import numpy as np; print(np.core.numeric.dtype(type(np.int64))"
        python -c "import pandas as pd; i = pd.Index([1,2,3]); print(i.max()); print(i.min())"
    - name: Test with pytest
      run: |
        pytest -m 'not slow and not network and not clipboard' pandas -n auto
      continue-on-error: true

#    - name: Publish test results
#      uses: actions/upload-artifact@master
#      with:
#        name: Test results
#        path: test-data.xml
#      if: failure()
#
#    - name: Print skipped tests
#      run: |
#        python ci/print_skipped.py
#
#    - name: Report Coverage
#      run: |
#        coverage report -m
#
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        flags: unittests
#        name: codecov-pandas
#        fail_ci_if_error: true
